### ISSUE TITLE
Joi error

### ISSUE THREAD

**Issue by moremi** [AndrewKeig/express-validation#102]
TypeError: Joi.validate is not a function at validate (\node_modules\express-validation\lib\index.js:75:7)

    "@hapi/joi": "^17.1.0",
    "@types/hapi__joi": "^16.0.12",
    "express-validation": "^2.0.0",

**Comment by AndrewKeig** [comment]
hey joi 17, removes the validate function, switch to joi 15, version 3 of this module will support joi 17, should be available in a couple of weeks.
