### ISSUE TITLE
Validation of multipart/form-data

### ISSUE THREAD

**Issue by jeremiedubuis** [AndrewKeig/express-validation#107]
Hi, first I'd like to thank you for the lib that allowed me to save quite some time moving hapi server routes to an express server.

I can't seem to find any information on how to handle multipart/form-data payloads using express-validation. Is this handled ? From what I gather hapi uses a payload option outside of the validation object (https://hapi.dev/api/?v=19.1.1#-routeoptionspayloadallow) to handle the parsing of different ContentTypes, could this be added to express-validation options ?

**Comment by AndrewKeig** [comment]
hey @jeremiedubuis, many thanks.  So we simply call jois validate function on the payload supplied, so if joi can validate multipart so can we :), you can of course use https://github.com/expressjs/multer to parse that data,  this library should be able to validate the payload, if you so wish.

**Comment by jeremiedubuis** [comment]
Oh thanks for that quick reply, I was wondering if any parsing was done on your side but I simply added a middleware function to pass the multipart data into req.body and everything is working now. Thanks again and sorry for the invonvenience.
