### ISSUE TITLE
express-validation does not mutate object

### ISSUE THREAD

**Issue by Heartz66** [AndrewKeig/express-validation#108]
Whenever I run this code:
```
var Joi = require("@hapi/joi");

let test = Joi.object({
    filters: Joi.object({
        appId: Joi.string().valid(...['730']).default('730'),
    }).required()
});

console.log(test.validate({
    filters: {}
}));
```

I get this as result, as excepted:
```
{
    filters: {
        appId: "730"
    }
}
```

Whenever I put the Joi.object() of above in express-validation for the body, it will return:

> {
>     filters: {}
> }

Is this as excepted? Does express-validation not mutate the objects like Joi does?

**Comment by Heartz66** [comment]
This happens because the `handleMutation` function only checks the first layer and does not check any nested objects. Isn't it easier to just replace the `body` parameter with the result of Joi validate in case of successful validation?

**Comment by AndrewKeig** [comment]
If you look in the docs, you can configure this to work by setting context to true.

https://github.com/AndrewKeig/express-validation#options-object

**Comment by Heartz66** [comment]
> If you look in the docs, you can configure this to work by setting context to true.
> 
> https://github.com/AndrewKeig/express-validation#options-object

Doesn't work, reading the docs I am unable to determine if the `context` variable is the way to solve this.

It happens because the `handleMutation` function only compares the keys of the first layer of the json, it doesn't compare inside nested objects. My first message contains a nested object with a default string, this string is not added being checked by the `handleMutation` check. I don't understand why using `handleMutation` is better instead of just replacing the `req.body` with the result returned by Joi itself? That would completely solve this bug.

**Comment by Heartz66** [comment]
See this Runkit: https://runkit.com/heartz66/5e6cdf90115e4a001ad62c00

**Comment by AndrewKeig** [comment]
hey @Heartz66, do you think you could put a pr together with a passing test.  I simply dont have time to resolve this, until late next week,  would really appreciate it.

**Comment by Heartz66** [comment]
I'll give it a try

**Comment by Heartz66** [comment]
I found the cause of this issue: the new express-validation wraps the body object inside a Joi object, joi objects don't handle defaults of nested Joi objects.. I will try to find a solution/workaround for this

**Comment by thenephew** [comment]
@Heartz66 did you manage to get this working?

I am facing the same issue with the following code:
```
validate({
    body: Joi.object({
      amount: Joi.number().required(),
      commission: Joi.number().min(0).max(1).default(config.platformCommission),
      price: Joi.number().min(0).default(0)
    })
})
```
The default values for `commission` and `price` are not assigned.

**Comment by Heartz66** [comment]
> @Heartz66 did you manage to get this working?
> 
> I am facing the same issue with the following code:
> 
> ```
> const { Joi, validate } = require('express-validation');
> ...
> validate({
>     body: Joi.object({
>       amount: Joi.number().required(),
>       commission: Joi.number().min(0).max(1).default(config.platformCommission),
>       price: Joi.number().min(0).default(0)
>     })
> })
> ```
> 
> The default values for `commission` and `price` are not assigned.

I haven't been able to find a solution for this yet, it's a `Joi` thing, it's not related to `express-validation`.

**Comment by thenephew** [comment]
@Heartz66  setting the `{ context: true }` solves the issue, though the docs mention other use cases for `context`

@AndrewKeig maybe it would be good to mention this in the docs. Default values worked prior to **ver 2**

**Comment by andrewcpacifico** [comment]
I'm having a similar issue, caused by some params defined as number:

```javascript
taskRouter.route('/')
  .get(validate({
    query: Joi.object({
      dueDate: Joi.date(),
      limit: Joi.number().integer().positive(),
      offset: Joi.number().integer().min(0),
    }),
  }), task.list);
```

When I try to use the `limit` and `offset` on my express handler, they are still strings.

Looking in the express-validation history, I saw that this line ensured the `request` mutation in the past: https://github.com/AndrewKeig/express-validation/blame/0c1bb7df38570fcfbdc0d28eb6f16f838957c0af/lib/index.js#L77 ... Is that correct? If it is, there is another way to have this behavior on this version? Or this behavior was removed for some reason?

My applications use an old version of express-validation, and when I tried to update I got this problem. @AndrewKeig maybe this behavior of mutate the `request` object could be defined as an option passed through `evOptions`? If it is ok, I can make a PR adding this option.

**Comment by Heartz66** [comment]
> _Joi should set default if you use `Joi.object().default()` for both parent and nested oject_
 
It does set the defaults but only if the object is empty, if 1 field is not empty it won't default the whole object.

**Comment by sikorsky555** [comment]
I haven't been able to get this to work either using the latest of express-validation and @hapi/joi. Is there a solution for this?

**Comment by sikorsky555** [comment]
After looking at it a little more, it seems like the defaults were working as expected. The thing which is different is the type that was generated before in this scenario. 

Before Joi.date().iso() would set that object to a Date object. Now it is simply a string which breaks other parts of our application. Is there any way to force it to mutate so this will work. I have pulled in express-joi-validation which seems to do this, but it would be nice to not be dependent on another library.

**Comment by andrewcpacifico** [comment]
Two weeks ago I opened a PR to add a `mutate` option: https://github.com/AndrewKeig/express-validation/pull/115

On my project I'm using the fork I created and it's working very well so far. I think the change I proposed on that PR can fix all problems related here.

**Comment by AndrewKeig** [comment]
hey, thanks for this, see #115 for response.

**Comment by sikorsky555** [comment]
@andrewcpacifico I tried with context and it indeed does not work, as I would expect. The following information should shed some light on it. This indeed looks like a change in behavior from express-validation from before. Also linking to documentation from hapi.

https://hapi.dev/module/joi/api/?v=17.1.1#date 

"Generates a schema object that matches a date type (as well as a JavaScript date string or number of milliseconds). If the validation convert option is on (**enabled by default**), a string or number will be converted to a Date if specified."

https://hapi.dev/module/joi/api/?v=17.1.1#number

"If the validation convert option is on (**enabled by default**), a string will be converted to a number if specified. Also, if convert is on and number.precision() is used, the value will be converted to the specified precision as well."

With changes from the PR, I am noticing the behavior specified in their documentation. When using mutate, the Date object behaves exactly as expected. With context, it is broken. 

"@hapi/joi": {
      "version": "17.1.1",
      "resolved": "https://registry.npmjs.org/@hapi/joi/-/joi-17.1.1.tgz",
      "integrity": "sha512-p4DKeZAoeZW4g3u7ZeRo+vCDuSDgSvtsB/NpfjXEHTUjSeINAi/RrVOWiVQ1isaoLzMvFEhe8n5065mQq1AdQg==",
      "requires": {
        "@hapi/address": "^4.0.1",
        "@hapi/formula": "^2.0.0",
        "@hapi/hoek": "^9.0.0",
        "@hapi/pinpoint": "^2.0.0",
        "@hapi/topo": "^5.0.0"
      }
    },

With context (most assuredly broken from upgrading to the newer version of express-validation with @hapi/joi:
2020-05-18T00:00:00.000-06:00 most assuredly a string

With mutate
"2020-05-18T06:00:00.000Z"
constructor
function Date() { [native code] }

**Comment by sikorsky555** [comment]
If it is not possible to use the same workflow as before and express-validation will not support the default conversion by joi, I can work around it by using a different library, validating outside of middleware, or forking this and keeping that fork in sync with this library, but this is definitely not the same behavior as before.

**Comment by AndrewKeig** [comment]
hey @sikorsky555, makes more sense now, thanks for your persistence.  Ive release 2.05 to npm with this fix, all under the context switch, many thanks.
