### ISSUE TITLE
Async custom validation

### ISSUE THREAD

**Issue by alex-w0** [AndrewKeig/express-validation#111]
Is it possible to create a custom validator function that contains async stuff?

```
body: Joi.object({
    name: Joi.string().min(4).max(15).required(),
    email: Joi.string()
      .email()
      .custom(async (value) => {
        const user = await User.findOne({ email: value });
        if (user !== null) {
          throw new Error('user already exists')
        }
      })
      .required(),
    password: Joi.string().min(6).required(),
  })
```

**Comment by gbkwiatt** [comment]
So is there ? Came across same issue. Trying to do validation in database with async function. 
It works with non async, but with async it doesn't for return or error. 
Tried alos @hapi/Joi but same issue. Can't make it work

**Comment by AndrewKeig** [comment]
@alex-w0 @gbkwiatt , not sure this works with async functions, works with non async, if you find a solution please add a test and a pr, thanks.

https://github.com/sideway/joi/blob/master/API.md#anycustommethod-description
