### ISSUE TITLE
Bug "schema[parameter].validateAsync is not a function"

### ISSUE THREAD

**Issue by adriandarian** [AndrewKeig/express-validation#112]
I am using `express-validation v3.0.2` and `@hapi/joi v17.1.1`

I have a simple request 

```javascript
router.route("/register").post(validate(register), controller.register);
```

However, when I run my code it throws an error 

```schema[parameter].validateAsync is not a function```

I checked in the actual library and on `express-validation/lib/index.js:18:55` a function called to validateAsync is called. In vscode when I hovered over the function name it just said `any`, which means there is no definition for the function.

**Comment by Chechotkin** [comment]
@adriandarian 
I had the same error when my schema looked like this
query: { page: Joi.number().min(1), ...} 
But it should be like this
query: Joi.object({ page: Joi.number().min(1), ...})
wrapped in Joi.object

**Comment by colcodev** [comment]
Thanks, @Chechotkin, it's working!
I am using `express-validation v3.0.2`, `node v12.16.2` and `import { Joi } from 'express-validation'`.

**Comment by TechRova** [comment]
> @adriandarian
> I had the same error when my schema looked like this
> query: { page: Joi.number().min(1), ...}
> But it should be like this
> query: Joi.object({ page: Joi.number().min(1), ...})
> wrapped in Joi.object

When I call any route in my express server , I am getting this error 

    TypeError: schema[parameter].validateAsync is not a function

        at validate (/home/techrova/Videos/VideoStream/node_modules/express-validation/lib/index.js:18:55)
        at /home/techrova/Videos/VideoStream/node_modules/express-validation/lib/index.js:26:25
        at Array.map (<anonymous>)
        at /home/techrova/Videos/VideoStream/node_modules/express-validation/lib/index.js:26:8
        at Layer.handle [as handle_request] (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/layer.js:95:5)
        at next (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/layer.js:95:5)
        at /home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:335:12)
        at next (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:275:10)
        at Function.handle (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:174:3)
        at router (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:47:12)
        at Layer.handle [as handle_request] (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:317:13)
        at /home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:335:12)
        at next (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:275:10)
        at Function.handle (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:174:3)
        at router (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:47:12)
        at Layer.handle [as handle_request] (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:317:13)
        at /home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:335:12)
        at next (/home/techrova/Videos/VideoStream/node_modules/express/lib/router/index.js:275:10)
        at cors (/home/techrova/Videos/VideoStream/node_modules/cors/lib/index.js:188:7)
        at /home/techrova/Videos/VideoStream/node_modules/cors/lib/index.js:224:17
        at originCallback (/home/techrova/Videos/VideoStream/node_modules/cors/lib/index.js:214:15)

I cannot understand what happening ? 

Please explain me ? 

Even I can't add details to this question , since I have no clue !!

I cant find out where this error occurs since the error message not showing the exact location and the function `validateAsync` not found in the code 

ParamValidation.js

```
import Joi from 'joi';

export default {
  createUser: {
    body: {
      userName: Joi.string().required(),
      dob: Joi.string().required(),
      email: Joi.string().regex(/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/).required().error(new Error('must be valid')).label('Email'),
      gender: Joi.string().required(),
      password: Joi.string().regex(/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&_*-]).{8,}$/).required().error(new Error('should be atleast 8, having One Caps, One Number, and One special character')).label('password format'),
    }
  },

  updateUser: {
    params: {
      userId: Joi.string().hex().required()
    }
  },

  login: {
    body: {
      username: Joi.string().required(),
      password: Joi.string().required()
    }
  },

  resetPassword: {
    body: {
      otp: Joi.string().required(),
      newPassword: Joi.string().required().regex(/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&_*-]).{8,}$/).error(new Error('should be atleast 8, having One Caps, One Number, and One special character')),
      confirmPassword: Joi.any().valid(Joi.ref('newPassword')).error(new Error('must match password')).label('password format')
    }
  },

  changePassword: {
    body: {
      oldPassword: Joi.string().required(),
      newPassword: Joi.string().required().regex(/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&_*-]).{8,}$/).error(new Error('should be atleast 8, having One Caps, One Number, and One special character')),
      confirmPassword: Joi.any().valid(Joi.ref('newPassword')).error(new Error('should be atleast 8, having One Caps, One Number, and One special character')).label('password confirm')
    }
  },

  activateUser: {
    query: {
      otp: Joi.string().hex().required()
    }
  },

  forgetUser: {
    query: {
      email: Joi.string().regex(/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/).required().error(new Error('must be valid')).label('Email')
    }
  },

  following: {
    query: {
      userId: Joi.string().required().label('userId'),

    }
  },

  createCategory: {
    body: {
      name: Joi.string().required().label('name'),
      discription: Joi.string().optional().label('discription'),
      category_img: Joi.string().required().label('category_img')
    }
  },

  contactUs: {
    body: {
      createdBy: Joi.string().optional(),
      fullName: Joi.string().required(),
      email: Joi.string().required(),
      message: Joi.string().required(),
    }
  },

  createPost: {
    body: {
      title: Joi.string().required().label('title'),
      discription: Joi.string().required().label('discription'),
      videoUrl: Joi.string().required().label('videoUrl'),
      isPaid: Joi.string().required().label('isPaid'),
      price: Joi.string().optional().label('price'),
      categoryId: Joi.string().required().label('categoryId'),

    }
  },

  createImagePost: {
    body: {
      title: Joi.string().required().label('title'),
      discription: Joi.string().optional().label('discription'),
      imageUrl: Joi.string().optional().label('imageUrl'),
      categoryId: Joi.string().required().label('categoryId'),

    }
  },

  getPost: {
    query: {
      userId: Joi.string().optional().label('userId'),
      isAll: Joi.string().required().label('isAll'),
      page: Joi.string().optional().label('page'),
      limit: Joi.string().optional().label('limit'),
      search: Joi.string().optional().label('search'),
      isPaid: Joi.string().optional().label('isPaid'),
      categoryId: Joi.string().optional().label('categoryId')
    }
  },

  getImagePost: {
    query: {
      userId: Joi.string().optional().label('userId'),
      isAll: Joi.string().required().label('isAll'),
      page: Joi.string().optional().label('page'),
      limit: Joi.string().optional().label('limit'),
      search: Joi.string().optional().label('search'),
      categoryId: Joi.string().optional().label('categoryId')
    }
  },

  handleLike: {
    query: {
      postId: Joi.string().required().label('postId'),
      isLike: Joi.string().required().label('isLike')
    }
  },

  views: {
    query: {
      postId: Joi.string().required().label('postId')
    }
  },
  createChat: {
    body: {
      receiverId: Joi.string().required().label('receiverId'),
      message: Joi.string().optional().label('message')
    }
  },
  createRoom: {
    body: {
      receiverId: Joi.string().required().label('receiverId')
    }
  },
  getChat: {
    query: {
      roomId: Joi.string().required().label('roomId')
    }
  },
  userChatRoom: {
    query: {
      userId: Joi.string().required().label('userId')
    }
  },
  payment: {
    body: {
      postId: Joi.string().required().label('postId'),
      tokenId: Joi.string().required().label('tokenId')
    }
  },
  blockUser: {
    query: {
      userId: Joi.string().required().label('userId'),
      isBlock: Joi.string().required().label('isBlock')
    }
  }

};
```

auth.route.js

```
import express from 'express';
import pkj from 'express-validation';
const {validate} =  pkj;
import expressJwt from 'express-jwt';
import paramValidation from '../../config/param-validation';
import authCtrl from '../controllers/auth.controller';

const router = express.Router(); // eslint-disable-line new-cap

router.route('/login')
  .post(validate(paramValidation.login), authCtrl.login);

router.route('/forgot-password')
  .get(validate(paramValidation.forgetUser), authCtrl.forgotPassword);

router.route('/reset-password')
  .post(validate(paramValidation.resetPassword), authCtrl.resetPassword);

router.route('/verify-otp')
  .get(authCtrl.verifyOTP);

router.route('/testotp')
  .post(authCtrl.testTwilio);

router.route('/checkprofilelink')
  .get(authCtrl.checkprofilelink);

router.route('/contactus')
  .post(validate(paramValidation.contactUs), authCtrl.addContactUs);

export default router;
```


Please help me ?

**Comment by frani** [comment]
@TechRova hi, did you try it with this changes ?

> @adriandarian
> I had the same error when my schema looked like this
> query: { page: Joi.number().min(1), ...}
> But it should be like this
> query: Joi.object({ page: Joi.number().min(1), ...})
> wrapped in Joi.object
