### ISSUE TITLE
Return schema context using HTTP GET requests

### ISSUE THREAD

**Issue by vickyrathee** [AndrewKeig/express-validation#114]
I want to use the same schema to return defaults for HTTP GET and POST, and it's working fine for POST requests. 

But how can I return the same context using GET request as well filled with default() values. My API will allow GET/POST with same schema.

```
const schema = {
            body :Joi.object().keys({
                url: Joi.string().required(),
                region: Joi.string().default('US'),
                limit: Joi.number().default(10)
            })
        };

router.get('/', async function (req, res, next) {
    console.log(req.query.url);
    // print http://example.com
    try {
        var context = validate(schema, { context: true }, {})
        res.json(context);
    } catch (error) {
        error.statusCode = 400;
        next(error);
    }
});
```

It should return

```
{
 url: http://example.com',
 region: 'US',
 limit: 10
}
```

**Comment by vickyrathee** [comment]
This is how I am doing the GET validation using Joi directly. Looking for a way to do it using `express-validation`

```
const schema = Joi.object().keys({
                url: Joi.string().required(),
                region: Joi.string().default('US'),
                limit: Joi.number().default(10)
            });
       

 const { error, value } = schema.validate({ url: req.query.url });
        if(error){
 return res.status(400).json(error) 
};
```

**Comment by AndrewKeig** [comment]
@vickyrathee, not sure I quite understand the issue, please look at the integration tests for examples, this one has tests related to default values:

https://github.com/AndrewKeig/express-validation/blob/master/__tests__/integration/defaultValues.test.js
