### ISSUE TITLE
Cookie validation

### ISSUE THREAD

**Issue by aymericbeaumet** [AndrewKeig/express-validation#12]
I wonder if there was a specific reason to omit the cookies validation? I'm currently facing the use-case where I need to do a preliminary check for a cookies before using its content.

**Comment by mrgamer** [comment]
I don't think there is any reason, and I find your need completely in line with this module, validation for express.js.
It can be added, and should not take many LOCs, so expect that soon, or, if you prefer, provide a PR yourself

**Comment by aymericbeaumet** [comment]
Yeah I will take care of it

**Comment by aymericbeaumet** [comment]
https://github.com/AndrewKeig/express-validation/pull/14
