### ISSUE TITLE
Links to Joi website for documentation are not working.

### ISSUE THREAD

**Issue by deepak-hce** [AndrewKeig/express-validation#126]
### **Joi.ref, Joi.defaults, and Joi.options are not opening in the documentation. Needs to update the latest links.**

![image](https://user-images.githubusercontent.com/47603898/96332619-c6adbd80-1082-11eb-960f-5dfb76f87d71.png)

**### After opening all the links, a black page with a header only opens. See the screenshot below.**

![image](https://user-images.githubusercontent.com/47603898/96332696-1be9cf00-1083-11eb-93a8-f9897caf98ca.png)

**Comment by cpitkin** [comment]
Links should be updated to: https://joi.dev/

**Comment by deepak-hce** [comment]
> Links should be updated to: https://joi.dev/

Yes
