### ISSUE TITLE
error: TypeError: external_express_validation_default(...) is not a function

### ISSUE THREAD

**Issue by tytom2003** [AndrewKeig/express-validation#142]
My program show below error. How to solve the error? Thank you.
.post(external_express_validation_default()(articlevalidation), article_controller.articlePost);
TypeError: external_express_validation_default(...) is not a function

article.route.js
import express from 'express';
import validate from 'express-validation';
import articleCtrl from '../controllers/article.controller';
import paramValidation from '../../config/param-validation';
const router = express.Router();
router.route('/')
  .get(articleCtrl.articleGet) 
  .post(validate(paramValidation.createArticle), articleCtrl.articlePost); 
router.route('/:article_id')
  .put(articleCtrl.articlePut) 
  .delete(articleCtrl.articleDelete); 
export default router;

param-validation.js
import Joi from 'joi';
export default {
  // POST /api/article
  createArticle: {
    body: {
      user_id: Joi.number().required(), 
      article_title: Joi.string().required(), 
      article_tag: Joi.string().required(), 
      article_content: Joi.string().min(20).required() 
    }
  },
  // POST /api/user
  createUser: {
    body: {
      user_name: Joi.string().required(), 
      user_mail: Joi.string().email().trim().required(), 
      user_password: Joi.string().regex(/[a-zA-Z0-9]{6,30}$/).required() 
    }
  }
};

**Comment by papandreou** [comment]
Sorry, this report is a bit of a mess. You should always try to provide a minimal reproduction. This spans multiple files, some of which aren't included (`../controllers/article.controller'
