### ISSUE TITLE
JSON.parse(res.text) returns "Unexpected token &"

### ISSUE THREAD

**Issue by poliveira89** [AndrewKeig/express-validation#15]
On my tests I handle the response just like documentation suggest. But I receive this error `Unexpected token &`.

**Comment by poliveira89** [comment]
This output it happens on the client-side as well. 

On your middleware function, you are sending TEXT with `&quote;` instead a string with `\"`

**Comment by pht-prakhar** [comment]
I am having same issue.
This is because the error message thrown from the middleware is not a JSON object

**Comment by pht-prakhar** [comment]
Use this to remove the error.

app.use(function (err, req, res, next) {
    if (err.message === 'validation error') {
        res.status(err.status).json(err);
    } else {
        next(err);
    }
});

**Comment by selbest** [comment]
@pht-prakhar  but your solution not work for me.
could I define the the error message type from the middleware

**Comment by colthreepv** [comment]
I think this issue is very old, and now errors have a specific Error Class (ValidationError), so checking for message seems less robust.

Feel free to re-open if things seems still broken on your end
