### ISSUE TITLE
joiOptions context not found

### ISSUE THREAD

**Issue by joseluisdominguez** [AndrewKeig/express-validation#153]
Hi, I triying send context such as joiOptions

```
const schema = [....]
const options = {
   context: true,
   keyByField: true,
   ...
}
const joiOptions = {
   context: {
      param1: 'valueContext'
   }
}
validate(schema, options, joiOptions)
```

Always, request object override joiOptions context (file lib/joi.js)

![image](https://user-images.githubusercontent.com/9901320/154134818-5c40c01c-03a2-4007-879b-1793f796e067.png)

**Comment by papandreou** [comment]
Fixed released in 4.0.0
