### ISSUE TITLE
Unable to validate arrays without context.

### ISSUE THREAD

**Issue by iheanyi** [AndrewKeig/express-validation#17]
So, this is more of a feature of Joi that is buggy but currently we can't do this with Express-Validation in order to use a reference value on an array. I think I know of a workaround/fix for this and that would be passing in an `allowContext` input at the validaton function [line 55](https://github.com/AndrewKeig/express-validation/blob/master/lib/index.js#L55) and then also making the default context equal to `false` in [these lines of code](https://github.com/AndrewKeig/express-validation/blob/master/lib/index.js#L36-L45). If `allowContext === true`, the request would get passed in as the context variable on [line 61](https://github.com/AndrewKeig/express-validation/blob/master/lib/index.js#L61). Let me know your thoughts on this. Thanks. 

```javascript
var Joi = require("joi");

var schema = {
  a: Joi.array().items(Joi.number().valid([1, 2, 3, 10, 11])),
  b: Joi.array().items(Joi.number().valid(Joi.ref('$a'))),
  c: Joi.any()
}

var example1 = {
  a: [1, 2, 3],
  b: [1, 2],
  c: 1
};

// Without context
Joi.validate(example1, schema, function(err, value) {
  if(err) {
    console.log("Error!");
    console.log(err);
    console.log(JSON.stringify(err.details)); 
  }

  console.log(value);
}); // Doesn't work properly, will throw errors.

// With context
Joi.validate(example1, schema, {context: example1}, function(err, value) {
  if(err) {
    console.log("Error!");
    console.log(err);
    console.log(JSON.stringify(err.details)); 
  }

  console.log(value);
}); // Works properly
```

**Comment by mrgamer** [comment]
sure, if specifying the context is all that it takes, well.. It's seems a nice workaround!
