### ISSUE TITLE
Feature request: remove unknown fields

### ISSUE THREAD

**Issue by boldt** [AndrewKeig/express-validation#21]
Until now, you have `allowUnknown*`, which make sure that keys not intended in the data are passed through or not. 

**This is a feature request**: 

Modify the options,  such that keys not intended to be in the data are dropped. The idea comed from [Paperwork](https://github.com/lperrin/paperwork#changes-from-1x):

*Paperwork now silently removes unknown fields from the validated blob. This is done so you never pass unvalidated data to your code. For instance, if an attacker was to pass an extra id, you might end up using it to update the wrong object in your database.*

I also pushed this idea for [isvalid](https://github.com/trenskow/isvalid/issues/8). There we use the following schema:

* `unknownBody` with the possible values of 'allow', 'deny', 'remove' 

Instad of `allowUnknown*: false` and `allowUnknown*: true`

The reason is the following: middleware frameworks such as Angular are sending a lot more framework specific data within the JSON, which I want to be removed.

**Comment by colthreepv** [comment]
The idea itself is not bad, I am a bit against the _silently remove fields_
In case a library _silently_ removes something, this has to be explicitly set in the options, not as default, as it can throw new developers off.

I don't actually see the security risk, either, but maybe I haven't seen a good example.
Let's suppose an API expects:
```javascript
var Joi = require('joi');

module.exports = {
  body: {
    email: Joi.string().email().required(),
    password: Joi.string().regex(/[a-zA-Z0-9]{3,30}/).required()
  }
};
```

And an attacker sends a JSON file comprised of 57 fields besides `email` and `password`, if your REST API code **only relies** on `req.body.email` and `req.body.password`, they would be *still* validated in case they are valid.
It seems something like "avoid developers to make stupid mistakes" but that is not the scope of the lib :)

**Comment by boldt** [comment]
At the moment `allowUnknown*` are set to true by default. I did nit suggest to set the `remove` as the default. 

 In case a library silently removes something, this has to be explicitly set in the options, not as default, as it can throw new developers off.

The next days, I will create an example for you.

**Comment by colthreepv** [comment]
Added `wontfix` for now as I don't agree removing parts of request payload adding this library to an existing project (it could create more havoc than profit)

Feel free to re-open with examples or a PR making this feature behind a flag

**Comment by francescovigolungo** [comment]
I found a workaround, with `customSanitizer`

```
sanitize('*').customSanitizer((value, { req, location, path }) => {
       if(path === 'field_to_delete'){
             delete req.body[path];
             return;
       }
       return value;
 })
```

**Comment by dubiousandrew** [comment]
Going off the previous post, you can create your own reusable function like this:

```
export const removeFieldsSanitizer = (remove: Array<string>) =>
  sanitize("*").customSanitizer((value, { req, location, path }) => {
    if (remove.find((v) => v === path)) {
      delete req.body[path];
      return;
    }
    return value;
  });
```

and use it like this:
```
router.post('/edit-user', 
[removeFieldsSanitizer(['password', 'username'])], (req, res)=>{...});
```

**Comment by parseshyam** [comment]
can we add configuration flag like allowUnknown: false/true. hence by doing so we can totally avoid any security vulnerability that might cause disaster!  
Here's the scenario : -
  
say my user model is
```
....
first_name: { type: STRING, allowNull: false },
last_name: { type: STRING, allowNull: false },
profile_pic: { type: STRING, defaultValue: null, allowNull: true, },
phone: { type: STRING(20), unique: true, allowNull: false },
phone_verified: { type: BOOLEAN, defaultValue: false, allowNull: false },
verify_code: { type: INTEGER, defaultValue: null    },
verify_exp: { type: BIGINT, defaultValue: null    },
.....

```

say for **user update** if my validation schema is as below:-

```
body('first_name').trim().escape().matches(/^[a-zA-Z ]*$/).withMessage(USER.FIRST_NAME_ERR),
body('last_name').trim().escape().matches(/^[a-zA-Z ]*$/).withMessage(USER.LAST_NAME_ERR),
body('profile_pic').trim().isURL().optional()
```

and for any user - update route say i'm updating user-model like so:-

```
await User.update({ ...req.body }, { where: { id: req.user.id } });
```
If JSON data contain any fields which belongs to user model it'll get passed ( even though if it's not in our validation schema) hence the update query will update all fields that passed which could be disastrous. 
if we can have a config field as mentioned **allowUnknown: false/true.** defaults to false we could avoid this. JOI does the same if the field is not in validation schema it'll prompt with a message like 'xyz field' is not allowed.
