### ISSUE TITLE
Allow to pass global joi options like: { presence: 'required' }

### ISSUE THREAD

**Issue by eyalw** [AndrewKeig/express-validation#23]
Please make it available to set the default for joi schema as { presence: 'required' },
I don't like setting .required() for each rule that I add, it's easier for me to specify .optional() when needed.
Also - allow to change this 'presence' setting per request (and not only global defaults).

If you agree with this I would be happy to send a PR.

**Comment by colthreepv** [comment]
This library is just a bridge to bring `Joi` messages to `expressjs`

Such option is available in the [Joi documentation](https://github.com/hapijs/joi/blob/v9.0.0-9/API.md#extendextension), as you can extend Joi, making a new object that requires any field that you create.
