### ISSUE TITLE
Content-Type is set to text/html

### ISSUE THREAD

**Issue by Naktibalda** [AndrewKeig/express-validation#26]
It could be my issue, but I have no idea what am I doing wrong.

How could I change Content-Type to application/json?

router:
```
router.get('/:id', [validate(validation.module.get)], controller.get);
```

validator:
```
var Joi = require('joi');

module.exports = {
    params: {
        id: Joi.number().required()
    }
};
```

Test code:
```
request(app)
    .get('/module/test')
    .set('Accept', 'application/json')
    .expect(400)
    .expect('Content-Type', /application\/json/)
    .end(function(err, res) {
        done();
    });
```

Error message:
```
Error: expected "Content-Type" matching /application\/json/, got "text/html; charset=utf-8"
```

**Comment by colthreepv** [comment]
I think this actually depend on the error handler middleware you are using in expressjs.

`express-validation` only throws an error to `next`,  that you should handle

**Comment by Naktibalda** [comment]
Thanks,

It appears that I had no error handler, because errorhandler was added before routes.
