### ISSUE TITLE
Response headers from error should be application/json

### ISSUE THREAD

**Issue by silverlight513** [AndrewKeig/express-validation#27]
The response of the error given by express-validation is `text/html; charset=utf-8` when it should be `application/json; charset=utf-8`. Because it is text/html responses given back are parsed as below:

```
{&quot;status&quot;:400,&quot;statusText&quot;:&quot;Bad Request&quot;,&quot;errors&quot;:[{&quot;field&quot;:&quot;content-type&quot;,&quot;location&quot;:&quot;headers&quot;,&quot;messages&quot;:[&quot;\&quot;content-type\&quot; must be one of [application/json;charset=UTF-8]&quot;],&quot;types&quot;:[&quot;any.allowOnly&quot;]}]}
```

**Comment by silverlight513** [comment]
Made some headway into changing the content type:

If the error handler is provided and the routes provide 4 params instead of the standard 2 (req, res) then json is sent.
```
app.use(function (err, req, res, next) {
  // specific for validation errors
  if (err instanceof ev.ValidationError) return res.status(err.status).json(err);

  // other type of errors, it *might* also be a Runtime Error
  // example handling
  if (process.env.NODE_ENV !== 'production') {
    return res.status(500).send(err.stack);
  } else {
    return res.status(500);
  }
});
```

**Comment by silverlight513** [comment]
I've been doing some messing about to see what's going on. The response has been broke since the change to force the consumer to handle the error in version 0.3.0. Version 0.2.0 seems to be the only working version. I've had to make my own fork and load in a version 0.2.0 which I got from npm as it's been removed from git and then make changes to make it complaint with current express.

**Comment by colthreepv** [comment]
Errors are objects and should be handled with an error-handler in your express application [as the example in home page](/AndrewKeig/express-validation#setup)  
The example uses `res.status(400).json(err);` this is a shortcut that sets the response as `application/json`

Using version prior as `0.3.0` gives the `application/json` header because the library doesn't use standard express middlware errors (not flexible!!!), to quote the changelog

> So from 0.3.0 onwards, you will need to add an express error handler, and return an error response.

**Comment by silverlight513** [comment]
This is what my set up looked like and it didn't seem to be handling the error responses within the error-handler.

```
var app = express();
var router = express.Router();

router.use(function(err, req, res, next){
  res.status(400).json(err);
});

router.route('/users').get(function(req, res) {
    // blah blah
});

app.use('/api', router);
```

I just noticed that the error handler on the readme.md is underneath the routes. Would that be why it's not being used on my implementation?

**Comment by silverlight513** [comment]
Yup, just tested it and that is what the issue is. Is there a reason why the order of such a thing would cause this to happen in express? Sorry, I'm extremely new to backend JS.

**Comment by colthreepv** [comment]
Order of middleware is relevant, express-middleware basically calls a `next(err)` with `err` being the JSON error.

So the next middleware receives this object, if there is not a next middleware in the chain of `/users` then it refers to the "global" chain, but it has to be defined after it.

It is a tricky implementation for newcomers, but it's not an express design, it is based off Ruby on Rails (afaik)
