### ISSUE TITLE
failed `npm install` with npm@3

### ISSUE THREAD

**Issue by okekhj** [AndrewKeig/express-validation#29]
NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead.

**Comment by colthreepv** [comment]
Acknowledged, where is the issue?
This only means you have to install `joi` in your project
