### ISSUE TITLE
Express-validation does not work with Joi 9

### ISSUE THREAD

**Issue by robwalkerexp** [AndrewKeig/express-validation#30]
[Joi 9](https://github.com/hapijs/joi/blob/v9.0.0-9/API.md) has new features that I would like to use for my project however express-validation requires a v8.x.x version of Joi.

Any chance of getting support for Joi 9?

**Comment by colthreepv** [comment]
Actually `express-validation` has joi as a peerDependency, so it's actually a "suggested" version.
You have to install Joi manually in your project.

I have tried installing `joi@9-beta` (that's the dist-tag for the beta) and express-validation 1.x, npm 3.x gives a WARN for peerdependency not respected, but it will let you install it.

Please note that express-validation has not been tested with joi9

**Comment by robwalkerexp** [comment]
I've done that and it works on NPM 3.x however I just realized that the machine this is failing on is running NPM 2.x. I'm looking at getting that upgraded to resolve the issue.

**Comment by holm** [comment]
It would be good if the restriction on Joi could be lifted a bit. While you can install Joi@9, you will not be able to shrinkwrap anymore (which we use).

**Comment by colthreepv** [comment]
Oh, I see. Never used shrinkwrap myself, so didn't know this would create
limitations.
Will merge at once, thanks for pointing this out

Il 19/ago/2016 23:20, "Christian Holm" <notifications@github.com> ha
scritto:
