### ISSUE TITLE
Upgrade to Joi ^9.0.4

### ISSUE THREAD

**Issue by mattstuhring** [AndrewKeig/express-validation#32]
Express-validation is requiring a version of Joi ^8.0.5.  But the most recent release of Joi is 9.0.4.  It would be great if this was updated so I can use the latest version of Joi.

**Comment by colthreepv** [comment]
Joi it's just a peerDependency, with npm 3.x you can install any version of peerDependency, it will just pop out a warning.

On the next commit I will update the package.json

**Comment by colthreepv** [comment]
#40 fixed this
