### ISSUE TITLE
or condition between params

### ISSUE THREAD

**Issue by sudhirbitsgoa** [AndrewKeig/express-validation#38]
```
api/v1/user?id='xxx'&name='sam'
````
Can we write validation to check atleast one of query param is present

**Comment by colthreepv** [comment]
I never had this need, but you can try this:

file: `test/validation/your-api.js`
```javascript
var Joi = require('joi');

module.exports = {
  params: Joi.object().min(1)
};
```

Please let us know if that works as expected ^_^

**Comment by colthreepv** [comment]
any update on this? does it work?
