### ISSUE TITLE
expresss validation to check id present in param and body are same

### ISSUE THREAD

**Issue by ShaileshDevadiga** [AndrewKeig/express-validation#41]
Hi,
I have a scenario where i need id present in  param and body to be same.
This is the validation schema i'm using:
```js
module.exports.post= {
  body: {
      id: Joi.string().valid(Joi.ref('$params.id')).required()
  }
};
```

and the test case:
```js
describe('when the schema contains an invalid reference to the request object', function() {
    it('should return a 400 response', function(done) {
      supertest(app)
        .post('/context/1')
        .send({id: '1'})
        .end(function(err, res) {
          if(err) {
            return done(err);
          }
          done();
        });
    });
  });
```
Even though the id's present in params and body are same I'm getting this response.
```json
{
  "status": 400,
  "statusText": "Bad Request",
  "errors": [
    {
      "field": "id",
      "location": "body",
      "messages": [
        "\"id\" must be one of [context:params.id]"
      ],
      "types": [
        "any.allowOnly"
      ]
    }
  ]
}
```

Can anyone please help me in understanding what i'm doing wrong?

**Comment by colthreepv** [comment]
the option `contextRequest` is missing in the options, you can find a [working example here](https://github.com/AndrewKeig/express-validation/blob/master/test/validation/context.js)

**Comment by ShaileshDevadiga** [comment]
I have added contextRequest in the options as you mentioned :+1: 
 module.exports.post= {
	options: { contextRequest: true },
  body: {
       id: Joi.string().valid(Joi.ref('$params.id')).required()
  }
};

but still it is giving me 400 bad request.

**Comment by colthreepv** [comment]
Sorry then, I think there must be something wrong with your codebase, which version of `express-validation` are you using?
There is an automated test that checks exactly for your use-case, so I presume this is working as expected in the library

**Comment by ShaileshDevadiga** [comment]
0.6.0

**Comment by colthreepv** [comment]
explained the problem... it's a feature of [1.0.0 release](https://github.com/AndrewKeig/express-validation#changelog)

**Comment by ShaileshDevadiga** [comment]
thanks it's working now
