### ISSUE TITLE
Schema validation using express-validation 

### ISSUE THREAD

**Issue by ShaileshDevadiga** [AndrewKeig/express-validation#47]
Is it possible to check conditional parameter using express-validation?
I want my JSON to have a value in  either a or b or both.If both of them doesn't have any value it should return 400 bad request.So I tried with 'OR' condition as given below.

Scenario:
payload= {  
                      body :  {
                             'properties' : Joi.object().keys({
                       'a':Joi.any(),
                       'b':Joi.any()
                     }).or('properties.a','properties.b')
                     }
 };

This is the payload i'm giving as input:

{
       "properties": {
            "a":"2123",
            "b":"1234"
    }
}

Even though i'm providing  both a and b i'm getting this response:

{
  "status": 400,
  "statusText": "Bad Request",
  "errors": [
    {
      "field": "properties",
      "location": "body",
      "messages": [
        "\"value\" must contain at least one of [properties.a, properties.b]"
      ],
      "types": [
        "object.missing"
      ]
    }
  ]
}

Can you help me with this situation?

**Comment by colthreepv** [comment]
If this is possible to be done with Joi, it's then possible to be done with this library.
If I have time, I will try an option like that myself
