### ISSUE TITLE
Give a name to your middleware help me Unit Test my routes

### ISSUE THREAD

**Issue by JulienStitelet** [AndrewKeig/express-validation#49]
Hi, 

Testing my routes, I list all middleware for my routes, and I want to assert 'Validate' middleware is implemented.
Currently, as it has no given name, it returns me <anonymous>.
A simple change at line 32 in index.js
from : return function (req, res, next)
to : return function Validate (req, res, next)
Now gives me "Validate" as handler name, and it's ok.

Do you think it's ok to add this change in next version ?
Thanks a lot

**Comment by colthreepv** [comment]
Im not a fan of exporting anonymous functions either, I agree.

**Comment by colthreepv** [comment]
Fixed!
