### ISSUE TITLE
stripUnknown

### ISSUE THREAD

**Issue by phpedinei** [AndrewKeig/express-validation#53]
Please, add support a stripUnknown

https://github.com/hapijs/joi/blob/master/API.md#validatevalue-schema-options-callback

Thanks

**Comment by colthreepv** [comment]
Okay, since 2.x is in a pre-release status I can add this smoothly.

It would be bliss to receive some tests in form of PR, I will publish the working code + doc today

**Comment by Matzu89** [comment]
@colthreepv what is the current status of this?

**Comment by colthreepv** [comment]
It's in the [2.x branch](https://github.com/AndrewKeig/express-validation/blob/2.x/lib/index.js#L53), [it does have tests](https://github.com/AndrewKeig/express-validation/blob/2.x/test/integration/strip-unknown.js)

Documentation seems missing :'(

**Comment by AndrewKeig** [comment]
Closing, released 3.0
