### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by liviuignat** [AndrewKeig/express-validation#54]
Hi,

Any plans to add typescript definitions?

Thanks.

**Comment by colthreepv** [comment]
I have plans :) I am using typescript, still this would be simple enough for this small library

**Comment by xeoneux** [comment]
@AndrewKeig @colthreepv any update on this?

**Comment by colthreepv** [comment]
Sorry I had no time to invest in this, It's my desire to do so, I estimate it's an afternoon work for a newbie typescript programmer.
express-validation it's quite short, most of it would be proxying Joi ts definitions.

I look into finding this afternoons time, but PRs or any input is welcome to speed me up

**Comment by fega** [comment]
I have this sketch, but I wasn't able to put parameters as Joi definitions, 
@colthreepv @xeoneux @AndrewKeig  any suggestions?
```
import { RequestHandler } from "express-serve-static-core";

interface Validator {
  body?: object;
  params?: object;
  query?: object;
  headers?: object;
  cookies?: object;
  options?: {
    allowUnknownBody?: boolean;
    allowUnknownHeaders?: boolean;
    allowUnknownQuery?: boolean;
    allowUnknownParams?: boolean;
    allowUnknownCookies?: boolean
  };
}

declare function validate(validator: Validator): RequestHandler;

export = validate;
```

**Comment by brunolm** [comment]
Nowadays it's possible to ship a TypeScript definition file with the package, you only need two things:

- create a `.d.ts` file with your package definitions, example from `moment`
https://github.com/moment/moment/blob/develop/moment.d.ts

- add `"typings": "./your-file.d.ts",` in package.json, example from `moment`
https://github.com/moment/moment/blob/develop/package.json#L27

**Comment by nivnahmias** [comment]
any updates on this issue?
