### ISSUE TITLE
TypeScript custom validator

### ISSUE THREAD

**Issue by Spoki4** [AndrewKeig/express-validation#56]
How I can an extend the validator with my validator functions? I do this:
```typescript
interface Validator extends ExpressValidator.Validator {
    isArray: () => ExpressValidator.Validator;
}

export interface IBaseRequest extends ExpressValidator.RequestValidation, express.Request {
    checkBody: {
        (item: string | string[], message?: string): Validator,
        (schema: {}): Validator
    };
}
```
when create express app: 
```typescript
app.use(validator({
     customValidators: {
         isArray: (value: any) => {
                return Array.isArray(value);
         }
     }
}));
```
but I think it's not a right solution. Can you help me or say how I can do this right.

**Comment by eliprand** [comment]
@dkMorlok can you elaborate on this? a code sample?
I get the gist of it, but I can't figure out where I am supposed to put this declaration of this to work.

**Comment by Britskiy** [comment]
@dkMorlok @eliprand same question here, can you show code sample?

**Comment by eliprand** [comment]
@Britskiy ,
Here is what I ended up doing:

Create a definition file (mine is `./definition.d.ts` ) and add the following:
```typescript
import 'express-validator';

declare module 'express-validator' {
    interface Validator {
        isPassword(): Validator;
    }
}
```

This will add `isPassword()` as a custom validator, provide intellisense and make sure things compile properly. Remember that you still have to actually register those custom validator during the bootstrapping of your application.

The definition file can be anything, anywhere, as long as it's in the compilation path. It shouldn't produce anything.

**Comment by Britskiy** [comment]
@eliprand thank you! now all works fine 👍
