### ISSUE TITLE
Upgrade to Joi 10

### ISSUE THREAD

**Issue by tex0l** [AndrewKeig/express-validation#58]
Hi,

I've seen you've already bumped joi in the master branch, but you haven't released it. The issue here is more to ask you to release a version that requires a peer dependency of joi@^10.0.0 :). Let me explain why:

I'm using express-validation (with joi) and vanilla joi somewhere else in my project. I use joi 10 and since the latest published version requires a peer dependency of joi@^9.0.4, I get the warning on install.

Well, it's usually no big deal: but I'm currently shrinkwraping my projects to lock dependencies versions. It appears you can't if a peer dependency is missing -_-. 

Since I use Joi 10 somewhere else in the project and that I can't have two versions of the same package in my package.json, I'm currently blocked for my shrinkwrap :/.

Can I expect a release in a near future?

Cheers,
tex0l.

**Comment by colthreepv** [comment]
okay, have you already tested it with Joi 10?
it's usually very smooth transition, just I had no time to read the changelog yet

**Comment by tex0l** [comment]
In my case it works fine, but I haven't tested it exhaustively:

Here are the joi changelogs: https://github.com/hapijs/joi/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22release+notes%22

**Comment by colthreepv** [comment]
What about using `peerDependencies: { "joi": "*" }` is that even valid?

This will offload responsability to end-users. that's exactly what always happens in those cases

**Comment by colthreepv** [comment]
Should be fixed in new `1.0.2` release, and this should put an end on the "bump" requests.

Side note: sorry for the general slowness, I left the library in the middle of a rewrite, that will see it's release very soon (I was hoping for a documentation review); now the repository has been tidy up to let simple releases like this go like a breeze (as they should!)
