### ISSUE TITLE
Change default status code at declaration

### ISSUE THREAD

**Issue by mrgamer** [AndrewKeig/express-validation#6]
I appreciate status code and status text can be customized by a per-validation basis, but what about changing globally at requre level?

As
```
var validation = require('express-validation')({ status: 422, statusText: 'Unprocessable Entity' });
```

**Comment by AndrewKeig** [comment]
Sure, makes sense, if you want this now i'm happy to take a pull request, otherwise I will get it in asap.

**Comment by mrgamer** [comment]
I did not provide a PR because the proposed change breaks the API big time...

everyone has to migrate their includes
```
// from
var validation = require('express-validation');
// to
var validation = require('express-validation')();
```

Seems ugly to me, and bad for your user-base... It would be cool to implement a runtime option system without breaking the API

**Comment by AndrewKeig** [comment]
Good point..  Will look into it and come up with a solution.
