### ISSUE TITLE
Joi any.error not working when function provided

### ISSUE THREAD

**Issue by blub0hr** [AndrewKeig/express-validation#63]
https://github.com/hapijs/joi/blob/v10.4.1/API.md#anyerrorerr

According to Joi docs one may provide a function to `.error`, however this does not change the error message when used with `express-validation`:

    Joi.string().lowercase().trim().required().error(() => "Please provide a string")

**Comment by colthreepv** [comment]
I have to re-read myself the issue n #59 that was about this API as well

**Comment by AndrewKeig** [comment]
Closing, released 3.0
