### ISSUE TITLE
No Way to Use Dependencies

### ISSUE THREAD

**Issue by spfurlong** [AndrewKeig/express-validation#64]
Not sure if this is an issue or maybe just a new feature but in Joi you can do something like this:

const schema = Joi.object().keys({
    a: Joi.any(),
    b: Joi.any()
}).xor('a', 'b');

where then it is saying you can have either a or b but not both and that ends up in a attribute called "dependencies" in the Joi Object. There seems to be no way to get that "xor" section into the Joi schema within express-validation

**Comment by colthreepv** [comment]
Usually express-validation doesn't really alter Joi functionality, it sounds strange to me.

It could be a simple problem of reference, usually in express-validation key reference is done with full path, example: `body.xyzkey` or `headers.x-sensitive-header`

Maybe set up a failing test and we'll fix it together

**Comment by AndrewKeig** [comment]
Closing, released 3.0
