### ISSUE TITLE
Hi AndrewKeig your repo is nice and i have made same work for restify framework of node?

### ISSUE THREAD

**Issue by awesomehimanshu** [AndrewKeig/express-validation#71]
https://github.com/awesomehimanshu/restify-validation

Thanks for good work. Will improve it more and if get any improvement in your repo will send you pull request.

There are lot of thing to improve when it come to complex body manipulation.

**Comment by colthreepv** [comment]
> There are lot of thing to improve when it come to complex body manipulation.

Interesting, I am away from this project for awhile, could you post some examples?

**Comment by AndrewKeig** [comment]
Closing, released 3.0
