### ISSUE TITLE
Add option allowEmptyBody: Boolean

### ISSUE THREAD

**Issue by fega** [AndrewKeig/express-validation#74]
It could be useful when you need a patch request that shouldn't be empty, but none of the parameters are required (only you update whatever you need)

**Comment by biblicalph** [comment]
@fega Can you provide some more information on the above? I can't really understand your use case or how to reproduce it

**Comment by fega** [comment]
for example I want to send a PATCH request with the fields to patch in the body.

so all of the fields are optional to send, but body shouldn't be empty (because it is a nonsense)

**Comment by fega** [comment]
Hello @biblicalph there is any thougths about? :)

**Comment by AndrewKeig** [comment]
Closing, released 3.0
