### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by arb** [AndrewKeig/express-validation#90]
Is this project still actively being maintained? The last commit was over 2 years ago and the used version of joi is several major versions behind.

**Comment by fega** [comment]
I'd like to maintain it

**Comment by colthreepv** [comment]
I think a good start would be reviewing development branches or Pull requests

Then I suggest to email AndrewKeig directly after you have a plan of action, eg:
- what to merge
-what not
-why
-there will be a next release?

**Comment by arb** [comment]
I ask because there are quite a few joi + express validation libraries out there so I'm wondering if this is not still being maintained, we could suggest alternatives.

**Comment by colthreepv** [comment]
That's also an option, if they provide a better support and similar/overlapping features I think it's viable.

From a (very) quick google search I didn't see anything **way** better supported/used etc.. but I can be wrong, hope to be wrong 😁

**Comment by arb** [comment]
https://github.com/arb/celebrate is the one I maintain and seems to be feature compatible. I'd certainly be open to merging the two projects. One potential hiccup would be the version of joi mismatch. celebrate uses newest while express-validation lists joi as a peerDep.

**Comment by fega** [comment]
@arb good project, I don't think that it will be a problem, since Joi api is pretty stable,

What I miss from your project is the options that this repo have like      allowUnknownBody

**Comment by arb** [comment]
@colthreepv you can achieve that with basic joi schemas without needing to add any code to celebrate.

**Comment by fega** [comment]
@colthreepv that would be awesome

**Comment by arb** [comment]
So you're looking for a PR to add a migration guide to the README or just a migration guide posted here on this issue?

**Comment by colthreepv** [comment]
Definitely a PR, I hope more contributors might see it and agree on this line of progress.
Maybe you can even ping Andrew and the contributors listed in the `package.json`

**Comment by johndcarmichael** [comment]
I just saw this "issue" after leaving a comment on my pr. This is great news it will be maintained, any chance we can get the dependency moved over to `@hapi/joi`? My pr is a pretty trivial drop in replacement and all tests are passing except a dependency on the ... operator fails travis. But supported anything older that the latest LTS of node seems a little pointless? 

(I had to update the mix tests to expect an array of strings opposed to a simple string in the errors.field)

**Comment by colthreepv** [comment]
I am happy to see newfound activity on this project, but I have to admit I am against useless proliferation of npm libraries.

Having said that I am not against activity on this project that I found particularly useful in the past, I just hope that time spent contributing to opensource is as meaningful as possible

Towards that, I am quite convinced by @arb when he declares that [celebrate](https://github.com/arb/celebrate) can be a good replacement for `express-validation`

As suggested before a simple migration guide could suffice in my opinion, with a `deprecated` warning on npm installs  

@aymericbeaumet @isaachinman

**Comment by arb** [comment]
I completely agree @colthreepv! While choice can be good, it is, at times overwhelming. 

Again, it it _not_ my intention to torpedo this lib. If it is secure and maintained, then it's fine. I only wrote celebrate because I was unable to find a joi + express middleware that worked how I believe it should.

**Comment by isaachinman** [comment]
I am using this package in production in several places and am willing/able to maintain it.

However, if `celebrate` (despite a terrible name) is indeed a 1:1 replacement _and_ someone writes a nice migration guide, I will personally consider moving everything over, and imagine others would too.

**Comment by arb** [comment]
`celebrate` is an _amazing_ name and it even has a logo! You celebrate your valid API arguments with joi! 😆

How would you want the migration guide? As a PR or wiki or?

**Comment by isaachinman** [comment]
My point about the name was that it's not very searchable - I had never heard of it prior to this.

Let's start with a PR for a separate `MIGRATE_TO_CELEBRATE.md` doc, and potentially move it into the main README in the future.

**Comment by isaachinman** [comment]
@arb One thing I'm wondering - does your package support imperative validation? There are times when requests need to be validated at runtime outside a middleware. #82 handles that for `express-validation`.

**Comment by arb** [comment]
In that instance you'd just use `joi` directly rather than expanding the surface area of celebrate or express-validation.

**Comment by isaachinman** [comment]
@arb No, I'd expect to receive a validation object in the exact same format.

**Comment by arb** [comment]
You'd expect a validation object that's the same shape as the result of `celebrate` (as documented [here](https://github.com/arb/celebrate#errors)) or the same shape that the celebrate error handler spits out?

**Comment by isaachinman** [comment]
> the same shape as the result of celebrate

Yes.
