### ISSUE TITLE
Error in package Joi

### ISSUE THREAD

**Issue by IuryBrasileiroMaiaSilva** [AndrewKeig/express-validation#92]
The package joi was changed to @hapi/joi.

Erro: Cannot find module 'joi'.

It was necessary to change from joi to @hapi/joi at lib/index.js

**Comment by juliuscc** [comment]
#96 should fix this

**Comment by exislow** [comment]
@AndrewKeig could you please accept the PR #96. A fix would be great.

**Comment by AndrewKeig** [comment]
Closing, released 3.0
